export const pizzas = [
  {
    id: 1,
    name: "Margherita",
    ingredients: ["pomodoro", "mozzarella"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 2,
    name: "Marinara",
    ingredients: ["pomodoro", "aglio", "origano"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 3,
    name: "Diavola",
    ingredients: ["pomodoro", "mozzarella", "salame piccante"],
    img: "pizza-default.jpg",
    isAvailable: false,
  },
  {
    id: 4,
    name: "Quattro Formaggi",
    ingredients: ["mozzarella", "gorgonzola", "fontina", "parmigiano"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 5,
    name: "Capricciosa",
    ingredients: [
      "pomodoro",
      "mozzarella",
      "prosciutto",
      "funghi",
      "carciofi",
      "olive",
    ],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 6,
    name: "Prosciutto e Funghi",
    ingredients: ["pomodoro", "mozzarella", "prosciutto", "funghi"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 7,
    name: "Napoli",
    ingredients: ["pomodoro", "mozzarella", "acciughe", "origano"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 8,
    name: "Tonno e Cipolla",
    ingredients: ["pomodoro", "mozzarella", "tonno", "cipolla"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 9,
    name: "Boscaiola",
    ingredients: ["pomodoro", "mozzarella", "salsiccia", "funghi"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 10,
    name: "Vegetariana",
    ingredients: [
      "pomodoro",
      "mozzarella",
      "peperoni",
      "zucchine",
      "melanzane",
    ],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 11,
    name: "Hawaiana",
    ingredients: ["pomodoro", "mozzarella", "prosciutto cotto", "ananas"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 12,
    name: "Tartufata",
    ingredients: ["mozzarella", "crema di tartufo", "funghi", "salsiccia"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 13,
    name: "Gorgonzola e Noci",
    ingredients: ["mozzarella", "gorgonzola", "noci"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 14,
    name: "Frutti di Mare",
    ingredients: ["pomodoro", "mozzarella", "frutti di mare"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 15,
    name: "Patate e Salsiccia",
    ingredients: ["mozzarella", "patate", "salsiccia", "rosmarino"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 16,
    name: "Calzone",
    ingredients: ["pomodoro", "mozzarella", "prosciutto", "funghi", "ricotta"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 17,
    name: "Bufalina",
    ingredients: ["pomodoro", "mozzarella di bufala", "basilico"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 18,
    name: "Pesto e Stracciatella",
    ingredients: ["mozzarella", "pesto", "stracciatella"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 19,
    name: "Speck e Brie",
    ingredients: ["mozzarella", "speck", "brie"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 20,
    name: "Carbonara",
    ingredients: ["mozzarella", "guanciale", "uovo", "pecorino"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
  {
    id: 21,
    name: "Parmigiana",
    ingredients: ["pomodoro", "mozzarella", "melanzane", "parmigiano"],
    img: "pizza-default.jpg",
    isAvailable: true,
  },
];
